name: Push changes to nspah-platform-docs
on:
  push:
    branches:
      - feature/automatic_documentation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflows-and-wait@v1.6.3
        with:
          owner: quantori
          ref: feature/automatic_documentation
          repo: nsaph-platform-docs
          github_token: ${{ secrets.ACCESS_TOKEN }}
          workflow_file_name: deploy.yml
